title: Privatkopiera
url: https://stefansundin.github.io
baseurl: /privatkopiera
github_repo: stefansundin/privatkopiera
description: Privatkopiera enklare med detta tillägg.
author: Stefan Sundin
extension_id: jhjhnecocacdbhlkjgpdacoibidhmgdf
extension_name: privatkopiera

# posts
permalink: /news/:year-:month-:day-:title.html

# build
gems:
- jekyll-coffeescript
- jekyll-github-metadata
markdown: kramdown
kramdown:
  input: GFM
