title: Privatkopiera
url: https://stefansundin.github.io
baseurl: /privatkopiera
description: Privatkopiera enklare med detta tillägg.
author: Stefan Sundin
extension_id: jhjhnecocacdbhlkjgpdacoibidhmgdf
extension_name: privatkopiera

# posts
permalink: /news/:year-:month-:day-:title.html

# build
gems: [jekyll-coffeescript]
markdown: kramdown
kramdown:
  input: GFM

# github data
# https://help.github.com/articles/repository-metadata-on-github-pages/
github:
  repository_nwo: stefansundin/privatkopiera
  repository_url: https://github.com/stefansundin/privatkopiera
  clone_url: https://github.com/stefansundin/privatkopiera.git
  releases_url: https://github.com/stefansundin/privatkopiera/releases
  issues_url: https://github.com/stefansundin/privatkopiera/issues
